from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR / "data"
JOBS_DIR = DATA_DIR / "jobs"
DEFAULT_CREDENTIALS_PATH = BASE_DIR / "google_cloud.json"
EXAMPLES_DIR = BASE_DIR / "example_inputs"

VERTEX_MODELS = [
    "gemini-3-pro-image-preview",
    "gemini-2.5-flash-image-preview",
]

FAL_MODELS = {
    "fal-ai/hunyuan-image/v3/instruct/edit": {
        "label": "Hunyuan Image Edit",
        "payload_type": "instruct_edit",
        "output_formats": ["png", "jpeg"],
        "guidance_default": 3.5,
        "max_input_images": 3,
        "supports_num_images": True,
        "supports_guidance_scale": True,
        "supports_seed": True,
        "supports_safety_checker": True,
        "supports_output_format": True,
        "supports_image_size": False,
        "image_size_from_first_image": True,
    },
    "fal-ai/qwen-image-2/pro/edit": {
        "label": "Qwen Image 2 Pro Edit",
        "payload_type": "qwen_pro_edit",
        "output_formats": ["png", "jpeg", "webp"],
        "max_input_images": 3,
        "supports_num_images": True,
        "supports_seed": True,
        "supports_safety_checker": True,
        "supports_output_format": True,
        "supports_image_size": False,
        "image_size_from_first_image": True,
    },
    "fal-ai/hy-wu-edit": {
        "label": "HY-WU Edit",
        "payload_type": "hy_wu_edit",
        "image_sizes": [
            "auto",
            "square_hd",
            "square",
            "portrait_4_3",
            "portrait_16_9",
            "landscape_4_3",
            "landscape_16_9",
        ],
        "output_formats": ["png", "jpeg"],
        "max_input_images": 3,
        "supports_num_images": True,
        "supports_seed": True,
        "supports_safety_checker": True,
        "supports_output_format": True,
        "supports_image_size": True,
        "supports_sync_mode": True,
        "supports_num_inference_steps": True,
        "num_inference_steps_default": 30,
        "supports_enable_thinking": True,
        "enable_thinking_default": True,
    },
    "fal-ai/qwen-image-edit-2511": {
        "label": "Qwen Image Edit 2511",
        "payload_type": "instruct_edit",
        "image_sizes": [
            "square_hd",
            "square",
            "portrait_4_3",
            "portrait_16_9",
            "landscape_4_3",
            "landscape_16_9",
        ],
        "output_formats": ["png", "jpeg", "webp"],
        "guidance_default": 4.5,
        "max_input_images": None,
        "supports_num_images": True,
        "supports_guidance_scale": True,
        "supports_seed": True,
        "supports_safety_checker": True,
        "supports_output_format": True,
        "supports_image_size": True,
    },
    "fal-ai/flux-2-pro/edit": {
        "label": "FLUX.2 Pro Edit",
        "payload_type": "instruct_edit",
        "image_sizes": [
            "auto",
            "square_hd",
            "square",
            "portrait_4_3",
            "portrait_16_9",
            "landscape_4_3",
            "landscape_16_9",
        ],
        "safety_tolerance_levels": ["1", "2", "3", "4", "5"],
        "safety_tolerance_default": "2",
        "output_formats": ["jpeg", "png"],
        "guidance_default": 0.0,
        "max_input_images": None,
        "supports_num_images": False,
        "supports_guidance_scale": False,
        "supports_seed": True,
        "supports_safety_checker": True,
        "supports_output_format": True,
        "supports_image_size": True,
        "supports_safety_tolerance": True,
        "supports_sync_mode": True,
    },
    "fal-ai/bytedance/seedream/v5/lite/edit": {
        "label": "Seedream V5 Lite Edit",
        "payload_type": "instruct_edit",
        "image_sizes": ["auto_2K"],
        "guidance_default": 0.0,
        "max_input_images": 10,
        "supports_num_images": True,
        "supports_guidance_scale": False,
        "supports_seed": False,
        "supports_safety_checker": True,
        "supports_output_format": False,
        "supports_image_size": True,
        "supports_sync_mode": True,
    },
    "fal-ai/nano-banana/edit": {
        "label": "Nano Banana Edit",
        "payload_type": "nano_banana_edit",
        "image_sizes": ["auto"],
        "aspect_ratios": ["auto", "21:9", "16:9", "3:2", "4:3", "5:4", "1:1", "4:5", "3:4", "2:3", "9:16"],
        "resolutions": ["1K", "2K", "4K"],
        "safety_tolerance_levels": ["1", "2", "3", "4", "5", "6"],
        "safety_tolerance_default": "4",
        "output_formats": ["png", "jpeg", "webp"],
        "guidance_default": 0.0,
        "max_input_images": None,
        "supports_num_images": True,
        "supports_guidance_scale": False,
        "supports_seed": True,
        "supports_safety_checker": False,
        "supports_output_format": True,
        "supports_image_size": False,
        "supports_aspect_ratio": True,
        "supports_resolution": True,
        "supports_safety_tolerance": True,
        "supports_sync_mode": True,
        "supports_limit_generations": True,
        "limit_generations_default": True,
        "supports_enable_web_search": True,
    },
    "fal-ai/nano-banana-2/edit": {
        "label": "Nano Banana 2 Edit",
        "payload_type": "nano_banana_edit",
        "image_sizes": ["auto"],
        "aspect_ratios": ["auto", "21:9", "16:9", "3:2", "4:3", "5:4", "1:1", "4:5", "3:4", "2:3", "9:16"],
        "resolutions": ["0.5K", "1K", "2K", "4K"],
        "safety_tolerance_levels": ["1", "2", "3", "4", "5", "6"],
        "safety_tolerance_default": "4",
        "output_formats": ["png", "jpeg", "webp"],
        "guidance_default": 0.0,
        "max_input_images": None,
        "supports_num_images": True,
        "supports_guidance_scale": False,
        "supports_seed": True,
        "supports_safety_checker": False,
        "supports_output_format": True,
        "supports_image_size": False,
        "supports_aspect_ratio": True,
        "supports_resolution": True,
        "supports_safety_tolerance": True,
        "supports_sync_mode": True,
        "supports_limit_generations": True,
        "limit_generations_default": True,
        "supports_enable_web_search": True,
    },
    "fal-ai/gpt-image-1.5/edit": {
        "label": "GPT Image 1.5 Edit",
        "payload_type": "gpt_image_edit",
        "image_sizes": ["auto", "1024x1024", "1536x1024", "1024x1536"],
        "backgrounds": ["auto", "transparent", "opaque"],
        "qualities": ["low", "medium", "high"],
        "input_fidelities": ["low", "high"],
        "output_formats": ["png", "jpeg", "webp"],
        "max_input_images": None,
        "supports_num_images": True,
        "supports_seed": False,
        "supports_safety_checker": False,
        "supports_output_format": True,
        "supports_image_size": True,
        "supports_background": True,
        "supports_quality": True,
        "supports_input_fidelity": True,
        "supports_sync_mode": True,
        "quality_default": "high",
        "input_fidelity_default": "high",
    },
    "fal-ai/gemini-flash-edit/multi": {
        "label": "Gemini Flash Edit Multi",
        "payload_type": "gemini_flash_edit_multi",
        "image_sizes": ["auto"],
        "output_formats": ["png"],
        "guidance_default": 0.0,
        "max_input_images": None,
        "supports_num_images": False,
        "supports_guidance_scale": False,
        "supports_seed": False,
        "supports_safety_checker": False,
        "supports_output_format": False,
        "supports_image_size": False,
    },
    "xai/grok-imagine-image/edit": {
        "label": "Grok Imagine Image Edit",
        "payload_type": "grok_imagine_edit",
        "resolutions": ["1k", "2k"],
        "output_formats": ["jpeg", "png", "webp"],
        "guidance_default": 0.0,
        "max_input_images": 3,
        "supports_num_images": True,
        "supports_guidance_scale": False,
        "supports_seed": False,
        "supports_safety_checker": False,
        "supports_output_format": True,
        "supports_image_size": False,
        "supports_resolution": True,
        "supports_sync_mode": True,
    },
}

# BFL Labs (labs.us2.bfl.ai) — partner endpoints; requires BFL_API_KEY (not FAL_KEY).
BFL_MODELS = {
    "bfl-labs/partners/raspberryai/flux-2-pro": {
        "label": "FLUX.2 Pro (BFL partner — fashion eval)",
        "payload_type": "flux2_pro_partner",
        "base_url": "https://labs.us2.bfl.ai",
        "submit_path": "/partners/raspberryai/flux-2-pro",
        "image_sizes": [
            "auto",
            "square_hd",
            "square",
            "portrait_4_3",
            "portrait_16_9",
            "landscape_4_3",
            "landscape_16_9",
        ],
        "min_input_images": 2,
        "max_input_images": 10,
        "supports_seed": True,
        "supports_prompt_upsampling": True,
        "prompt_upsampling_default": False,
        "supports_safety_tolerance": True,
        "safety_tolerance_levels": ["1", "2", "3", "4", "5"],
        "safety_tolerance_default": "3",
        # API output is capped at 2048×2048; bfl_provider scales requested size down to fit.
        "max_output_side": 2048,
    },
    "bfl-labs/partners/raspberryai/flux-2-max": {
        "label": "FLUX.2 Max (BFL partner — fashion eval)",
        "payload_type": "flux2_pro_partner",
        "base_url": "https://labs.us2.bfl.ai",
        "submit_path": "/partners/raspberryai/flux-2-max",
        "image_sizes": [
            "auto",
            "square_hd",
            "square",
            "portrait_4_3",
            "portrait_16_9",
            "landscape_4_3",
            "landscape_16_9",
        ],
        "min_input_images": 2,
        "max_input_images": 10,
        "supports_seed": True,
        "supports_prompt_upsampling": True,
        "prompt_upsampling_default": False,
        "supports_safety_tolerance": True,
        "safety_tolerance_levels": ["1", "2", "3", "4", "5"],
        "safety_tolerance_default": "3",
        "max_output_side": 2048,
    },
}
